spring:
  application:
    name: Authentication

  server:
    port: 8080

  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    secret-key: nYGarGcYQyVQwIoJUw6F8Q6b70ZIjPIN
    expiration-time: 86400000